import {
    AiBrain01Icon,
    AiMagicIcon,
    AlarmClockIcon,
    Alert01Icon,
    AlertCircleIcon,
    Analytics01Icon,
    ApiIcon,
    Archive02Icon,
    ArrowDown01Icon,
    ArrowDownDoubleIcon,
    ArrowDownLeft01Icon,
    ArrowExpand01Icon,
    ArrowLeft01Icon,
    ArrowRight01Icon,
    ArrowShrink01Icon,
    ArrowTurnBackwardIcon,
    ArrowTurnForwardIcon,
    ArrowUp01Icon,
    ArrowUpDoubleIcon,
    ArrowUpRight01Icon,
    Attachment01Icon,
    Award01Icon,
    BatteryFullIcon,
    Blockchain01Icon,
    BluetoothIcon,
    Book01Icon,
    Bookmark02Icon,
    Briefcase01Icon,
    BubbleChatIcon,
    BubbleChatQuestionIcon,
    Bug01Icon,
    Building01Icon,
    Calendar01Icon,
    Calendar03Icon,
    Call02Icon,
    Camera01Icon,
    Cancel01Icon,
    CancelCircleIcon,
    ChartBarLineIcon,
    ChartDownIcon,
    ChartLineData01Icon,
    ChartUpIcon,
    CheckmarkBadge02Icon,
    CheckmarkCircle02Icon,
    CheckmarkSquare02Icon,
    Clock01Icon,
    CloudAngledRainIcon,
    CloudDownloadIcon,
    CloudIcon,
    CloudUploadIcon,
    CloudyIcon,
    CodeIcon,
    Coffee01Icon,
    ColorPickerIcon,
    Comment01Icon,
    CommandIcon,
    ComputerIcon,
    ComputerTerminal01Icon,
    Copy01Icon,
    CreditCardIcon,
    CropIcon,
    DashboardSquare01Icon,
    Database01Icon,
    Delete02Icon,
    Discount01Icon,
    DollarCircleIcon,
    Download01Icon,
    DragDropIcon,
    EyeIcon,
    File01Icon,
    FileAddIcon,
    FileDownloadIcon,
    FileEditIcon,
    FileEmpty02Icon,
    FileUploadIcon,
    FilterIcon,
    FingerPrintIcon,
    FireIcon,
    Flag02Icon,
    FlashIcon,
    Flowchart01Icon,
    Folder01Icon,
    FolderAddIcon,
    FolderLibraryIcon,
    FolderOpenIcon,
    FullScreenIcon,
    GiftIcon,
    GitBranchIcon,
    GitCommitIcon,
    GithubIcon,
    GitMergeIcon,
    GitPullRequestIcon,
    GlobalIcon,
    GridIcon,
    HeadphonesIcon,
    HelpCircleIcon,
    Home01Icon,
    Idea01Icon,
    Image01Icon,
    ImageAdd01Icon,
    InboxIcon,
    InformationCircleIcon,
    Invoice01Icon,
    Key01Icon,
    KeyboardIcon,
    LaptopIcon,
    Layers01Icon,
    Layout01Icon,
    Leaf01Icon,
    LeftToRightListBulletIcon,
    LeftToRightListNumberIcon,
    Link01Icon,
    LinkSquare01Icon,
    Loading03Icon,
    Location01Icon,
    LockIcon,
    Login01Icon,
    Logout01Icon,
    MagicWand01Icon,
    Mail01Icon,
    MailOpen01Icon,
    MapsIcon,
    Menu01Icon,
    Message01Icon,
    Mic01Icon,
    MicOff01Icon,
    MinusSignIcon,
    Moon02Icon,
    MoreHorizontalIcon,
    MoreVerticalIcon,
    Mouse01Icon,
    Move01Icon,
    MusicNote01Icon,
    Navigation03Icon,
    NextIcon,
    Note01Icon,
    Notification01Icon,
    NotificationOff01Icon,
    PackageIcon,
    PaintBoardIcon,
    PaintBrush01Icon,
    PaintBucketIcon,
    PauseIcon,
    PieChartIcon,
    PinIcon,
    PlayIcon,
    PlusSignIcon,
    PreviousIcon,
    PrinterIcon,
    PuzzleIcon,
    QuoteDownIcon,
    RefreshIcon,
    Robot01Icon,
    Rocket01Icon,
    Search01Icon,
    SecurityIcon,
    Sent02Icon,
    ServerStack01Icon,
    Settings01Icon,
    Share01Icon,
    Shield01Icon,
    SidebarLeft01Icon,
    SidebarRight01Icon,
    SmartPhone01Icon,
    SnowIcon,
    SortingAZ01Icon,
    SourceCodeIcon,
    SparklesIcon,
    SquareUnlock01Icon,
    StarIcon,
    StopIcon,
    Sun01Icon,
    Tag01Icon,
    Target01Icon,
    TaskDone01Icon,
    TextAlignCenterIcon,
    TextAlignLeftIcon,
    TextAlignRightIcon,
    TextBoldIcon,
    TextIcon,
    TextItalicIcon,
    TextStrikethroughIcon,
    TextUnderlineIcon,
    ThumbsDownIcon,
    ThumbsUpIcon,
    Ticket01Icon,
    Time02Icon,
    Timer01Icon,
    Unlink01Icon,
    Upload01Icon,
    UserAdd01Icon,
    UserCircleIcon,
    UserGroupIcon,
    UserIcon,
    UserRemove01Icon,
    UserSettings01Icon,
    ViewOffSlashIcon,
    Video01Icon,
    VolumeHighIcon,
    VolumeMute01Icon,
    Wallet01Icon,
    Watch01Icon,
    Wifi01Icon,
    ZoomInAreaIcon,
    ZoomOutAreaIcon,
    ShoppingBag01Icon,
    ShoppingCart01Icon,
    FavouriteIcon,
    Tick02Icon,
  } from "@hugeicons/core-free-icons"
  import { HugeiconsIcon, type IconSvgElement } from "@hugeicons/react"
  
  import type { IconCategoryId } from "./icon-categories"
  
  /**
   * The slice of Hugeicons this project actually uses, grouped by the categories
   * in `@/icons/icons-categories`. Keys are the names the app refers to an icon
   * by — stable, kebab-case, and unique across every group, so the flat lookup
   * below and the merged registry in `@/icons/icons` can key off them.
   *
   * Icons stay in their raw `IconSvgElement` form rather than being wrapped in a
   * component, so callers keep the full `HugeiconsIcon` surface (`size`,
   * `strokeWidth`, `altIcon`, and the rest).
   */
  export const hugeIcons = {
    interface: {
      home: Home01Icon,
      dashboard: DashboardSquare01Icon,
      grid: GridIcon,
      menu: Menu01Icon,
      "sidebar-left": SidebarLeft01Icon,
      "sidebar-right": SidebarRight01Icon,
      settings: Settings01Icon,
      search: Search01Icon,
      filter: FilterIcon,
      sort: SortingAZ01Icon,
      "more-horizontal": MoreHorizontalIcon,
      "more-vertical": MoreVerticalIcon,
      notification: Notification01Icon,
      "notification-off": NotificationOff01Icon,
      close: Cancel01Icon,
      plus: PlusSignIcon,
      minus: MinusSignIcon,
      refresh: RefreshIcon,
      loading: Loading03Icon,
      fullscreen: FullScreenIcon,
      "drag-drop": DragDropIcon,
      move: Move01Icon,
      "zoom-in": ZoomInAreaIcon,
      "zoom-out": ZoomOutAreaIcon,
      "log-in": Login01Icon,
      "log-out": Logout01Icon,
    },
    arrows: {
      "arrow-up": ArrowUp01Icon,
      "arrow-down": ArrowDown01Icon,
      "arrow-left": ArrowLeft01Icon,
      "arrow-right": ArrowRight01Icon,
      "arrow-up-right": ArrowUpRight01Icon,
      "arrow-down-left": ArrowDownLeft01Icon,
      "arrow-expand": ArrowExpand01Icon,
      "arrow-shrink": ArrowShrink01Icon,
      "chevrons-up": ArrowUpDoubleIcon,
      "chevrons-down": ArrowDownDoubleIcon,
      undo: ArrowTurnBackwardIcon,
      redo: ArrowTurnForwardIcon,
      link: Link01Icon,
      unlink: Unlink01Icon,
      "external-link": LinkSquare01Icon,
      location: Location01Icon,
      map: MapsIcon,
      globe: GlobalIcon,
      compass: Navigation03Icon,
    },
    files: {
      file: File01Icon,
      "file-empty": FileEmpty02Icon,
      "file-add": FileAddIcon,
      "file-edit": FileEditIcon,
      "file-download": FileDownloadIcon,
      "file-upload": FileUploadIcon,
      folder: Folder01Icon,
      "folder-add": FolderAddIcon,
      "folder-open": FolderOpenIcon,
      "folder-library": FolderLibraryIcon,
      copy: Copy01Icon,
      delete: Delete02Icon,
      archive: Archive02Icon,
      attachment: Attachment01Icon,
      bookmark: Bookmark02Icon,
      pin: PinIcon,
      flag: Flag02Icon,
      download: Download01Icon,
      upload: Upload01Icon,
      share: Share01Icon,
      note: Note01Icon,
      book: Book01Icon,
      "task-done": TaskDone01Icon,
      ticket: Ticket01Icon,
    },
    communication: {
      mail: Mail01Icon,
      "mail-open": MailOpen01Icon,
      message: Message01Icon,
      chat: BubbleChatIcon,
      comment: Comment01Icon,
      call: Call02Icon,
      "video-call": Video01Icon,
      send: Sent02Icon,
      inbox: InboxIcon,
      "chat-question": BubbleChatQuestionIcon,
    },
    users: {
      user: UserIcon,
      "user-add": UserAdd01Icon,
      "user-remove": UserRemove01Icon,
      "user-group": UserGroupIcon,
      "user-circle": UserCircleIcon,
      "user-settings": UserSettings01Icon,
      building: Building01Icon,
      briefcase: Briefcase01Icon,
      award: Award01Icon,
    },
    media: {
      image: Image01Icon,
      "image-add": ImageAdd01Icon,
      camera: Camera01Icon,
      play: PlayIcon,
      pause: PauseIcon,
      stop: StopIcon,
      next: NextIcon,
      previous: PreviousIcon,
      volume: VolumeHighIcon,
      mute: VolumeMute01Icon,
      mic: Mic01Icon,
      "mic-off": MicOff01Icon,
      headphones: HeadphonesIcon,
      music: MusicNote01Icon,
    },
    editor: {
      text: TextIcon,
      bold: TextBoldIcon,
      italic: TextItalicIcon,
      underline: TextUnderlineIcon,
      strikethrough: TextStrikethroughIcon,
      "align-left": TextAlignLeftIcon,
      "align-center": TextAlignCenterIcon,
      "align-right": TextAlignRightIcon,
      "list-bullet": LeftToRightListBulletIcon,
      "list-numbered": LeftToRightListNumberIcon,
      quote: QuoteDownIcon,
      brush: PaintBrush01Icon,
      "paint-bucket": PaintBucketIcon,
      "color-picker": ColorPickerIcon,
      palette: PaintBoardIcon,
      crop: CropIcon,
      layers: Layers01Icon,
      layout: Layout01Icon,
    },
    status: {
      alert: Alert01Icon,
      "alert-circle": AlertCircleIcon,
      info: InformationCircleIcon,
      help: HelpCircleIcon,
      check: Tick02Icon,
      "check-circle": CheckmarkCircle02Icon,
      "check-square": CheckmarkSquare02Icon,
      verified: CheckmarkBadge02Icon,
      "cancel-circle": CancelCircleIcon,
      heart: FavouriteIcon,
      star: StarIcon,
      "thumbs-up": ThumbsUpIcon,
      "thumbs-down": ThumbsDownIcon,
    },
    data: {
      analytics: Analytics01Icon,
      "chart-line": ChartLineData01Icon,
      "chart-bar": ChartBarLineIcon,
      "chart-pie": PieChartIcon,
      "trend-up": ChartUpIcon,
      "trend-down": ChartDownIcon,
      database: Database01Icon,
      server: ServerStack01Icon,
      cloud: CloudIcon,
      "cloud-upload": CloudUploadIcon,
      "cloud-download": CloudDownloadIcon,
      flowchart: Flowchart01Icon,
      target: Target01Icon,
    },
    development: {
      code: CodeIcon,
      "source-code": SourceCodeIcon,
      command: CommandIcon,
      terminal: ComputerTerminal01Icon,
      bug: Bug01Icon,
      "git-branch": GitBranchIcon,
      "git-commit": GitCommitIcon,
      "git-merge": GitMergeIcon,
      "git-pull-request": GitPullRequestIcon,
      github: GithubIcon,
      package: PackageIcon,
      api: ApiIcon,
      blockchain: Blockchain01Icon,
      puzzle: PuzzleIcon,
    },
  /*}  time: {
      calendar: Calendar01Icon,
      "calendar-schedule": Calendar03Icon,
      clock: Clock01Icon,
      time: Time02Icon,
      alarm: AlarmClockIcon,
      timer: Timer01Icon,
    }, */
    commerce: {
      wallet: Wallet01Icon,
      "credit-card": CreditCardIcon,
      cart: ShoppingCart01Icon,
      bag: ShoppingBag01Icon,
      tag: Tag01Icon,
      gift: GiftIcon,
      dollar: DollarCircleIcon,
      invoice: Invoice01Icon,
      discount: Discount01Icon,
      coffee: Coffee01Icon,
    },
  /*  devices: {
      smartphone: SmartPhone01Icon,
      laptop: LaptopIcon,
      computer: ComputerIcon,
      mouse: Mouse01Icon,
      keyboard: KeyboardIcon,
      watch: Watch01Icon,
      printer: PrinterIcon,
      wifi: Wifi01Icon,
      bluetooth: BluetoothIcon,
      battery: BatteryFullIcon,
    }, */
  /*  security: {
      lock: LockIcon,
      unlock: SquareUnlock01Icon,
      "security-check": SecurityIcon,
      shield: Shield01Icon,
      key: Key01Icon,
      fingerprint: FingerPrintIcon,
      eye: EyeIcon,
      "eye-off": ViewOffSlashIcon,
    }, */
  /*  nature: {
      sun: Sun01Icon,
      moon: Moon02Icon,
      cloudy: CloudyIcon,
      rain: CloudAngledRainIcon,
      snow: SnowIcon,
      flash: FlashIcon,
      fire: FireIcon,
      leaf: Leaf01Icon,
    }, */   
  /*  ai: {
      "ai-magic": AiMagicIcon,
      "ai-brain": AiBrain01Icon,
      sparkles: SparklesIcon,
      robot: Robot01Icon,
      "magic-wand": MagicWand01Icon,
      idea: Idea01Icon,
      rocket: Rocket01Icon,
    }, */
  } satisfies Partial<Record<IconCategoryId, Record<string, IconSvgElement>>>
  
  /** Category ids that actually carry Hugeicons marks. */
  export type HugeIconCategoryId = keyof typeof hugeIcons
  
  /** Flat `name -> mark` lookup, collapsed from the groups above. */
  export const hugeIconsByName = Object.fromEntries(
    Object.values(hugeIcons).flatMap((group) => Object.entries(group))
  ) as Record<HugeIconName, IconSvgElement>
  
  export type HugeIconName = {
    [Category in HugeIconCategoryId]: keyof (typeof hugeIcons)[Category]
  }[HugeIconCategoryId] &
    string
  
  export type HugeIconProps = Omit<
    React.ComponentProps<typeof HugeiconsIcon>,
    "icon"
  > & {
    /** A key from `hugeIconsByName`, e.g. `"chart-line"`. */
    name: HugeIconName
  }
  
  /** Renders a mark by name: `<HugeIcon name="chart-line" strokeWidth={2} />`. */
  export function HugeIcon({ name, ...props }: HugeIconProps) {
    return <HugeiconsIcon icon={hugeIconsByName[name]} {...props} />
  }