import { HugeiconsIcon } from "@hugeicons/react"
import {
  AlertCircleIcon,
  Analytics01Icon,
  AppWindowIcon,
  AppWindowMacIcon,
  ArrowDown01Icon,
  ArrowExpand01Icon,
  ArrowLeft02Icon,
  ArrowLeftRightIcon,
  ArrowRight01Icon,
  ArrowRight02Icon,
  ArrowUp01Icon,
  Attachment01Icon,
  BlurIcon,
  BrowserIcon,
  BubbleChatIcon,
  Calendar03Icon,
  CarouselHorizontalIcon,
  Chatting01Icon,
  CheckListIcon,
  CheckmarkSquare02Icon,
  ChevronDownIcon,
  Clock01Icon,
  CodeSquareIcon,
  Comment01Icon,
  CommandIcon,
  Copy01Icon,
  ColorsIcon,
  CropIcon,
  CursorPointer01Icon,
  Edit02Icon,
  GlobalIcon,
  GridViewIcon,
  HelpCircleIcon,
  HelpSquareIcon,
  HighlighterIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyboardIcon,
  Layers01Icon,
  Layout01Icon,
  LeftToRightListNumberIcon,
  ListViewIcon,
  Loading03Icon,
  Menu01Icon,
  Message01Icon,
  Minimize01Icon,
  MinusSignIcon,
  MoreHorizontalCircle01Icon,
  Mouse01Icon,
  MouseRightClick01Icon,
  Navigation03Icon,
  NoteIcon,
  Notification03Icon,
  PlusSignIcon,
  Progress01Icon,
  RadioButtonIcon,
  Resize01Icon,
  Route01Icon,
  RowInsertIcon,
  Search01Icon,
  SearchList01Icon,
  SentIcon,
  Settings01Icon,
  Share08Icon,
  ShoppingBag01Icon,
  SidebarBottomIcon,
  SidebarLeft01Icon,
  SidebarRight01Icon,
  SlidersHorizontalIcon,
  SmileIcon,
  SolidLine01Icon,
  Sorting01Icon,
  SquareLock01Icon,
  Table01Icon,
  Tag01Icon,
  Tap01Icon,
  TextFontIcon,
  TextIcon,
  TextSquareIcon,
  Tick02Icon,
  ToggleOffIcon,
  ToggleOnIcon,
  TranslateIcon,
  Trash,
  UserCircleIcon,
} from "@hugeicons/core-free-icons"

import type { IconCategoryId } from "./icon-categories"
import type * as React from "react"
import { cn } from "@/lib/utils"

/**
 * Central icon definitions for the app. Add new icons here so every usage
 * shares the same set and default styling.
 */
export const Icons = {
  alert: AlertCircleIcon,
  analytics: Analytics01Icon,
  appWindow: AppWindowIcon,
  appWindowMac: AppWindowMacIcon,
  arrowDown: ArrowDown01Icon,
  arrowExpand: ArrowExpand01Icon,
  arrowLeft: ArrowLeft02Icon,
  arrowLeftRight: ArrowLeftRightIcon,
  arrowRight: ArrowRight02Icon,
  arrowUp: ArrowUp01Icon,
  attachment: Attachment01Icon,
  colors: ColorsIcon,
  blur: BlurIcon,
  browser: BrowserIcon,
  bubbleChat: BubbleChatIcon,
  calendar: Calendar03Icon,
  carouselHorizontal: CarouselHorizontalIcon,
  chatting: Chatting01Icon,
  check: Tick02Icon,
  clock: Clock01Icon,
  code: CodeSquareIcon,
  checkList: CheckListIcon,
  checkmarkSquare: CheckmarkSquare02Icon,
  chevronRight: ArrowRight01Icon,
  command: CommandIcon,
  comment: Comment01Icon,
  copy: Copy01Icon,
  crop: CropIcon,
  cursorPointer: CursorPointer01Icon,
  delete: Trash,
  edit: Edit02Icon,
  globe: GlobalIcon,
  grid: GridViewIcon,
  helpCircle: HelpCircleIcon,
  helpSquare: HelpSquareIcon,
  highlighter: HighlighterIcon,
  inbox: InboxIcon,
  infoCircle: InformationCircleIcon,
  keyboard: KeyboardIcon,
  layers: Layers01Icon,
  layout: Layout01Icon,
  listNumber: LeftToRightListNumberIcon,
  listView: ListViewIcon,
  loading: Loading03Icon,
  menu: Menu01Icon,
  message: Message01Icon,
  minimize: Minimize01Icon,
  minus: MinusSignIcon,
  more: MoreHorizontalCircle01Icon,
  mouse: Mouse01Icon,
  mouseRightClick: MouseRightClick01Icon,
  navigation: Navigation03Icon,
  note: NoteIcon,
  notification: Notification03Icon,
  plus: PlusSignIcon,
  progress: Progress01Icon,
  radioButton: RadioButtonIcon,
  resize: Resize01Icon,
  route: Route01Icon,
  rowInsert: RowInsertIcon,
  search: Search01Icon,
  searchList: SearchList01Icon,
  sent: SentIcon,
  settings: Settings01Icon,
  share: Share08Icon,
  shoppingBag: ShoppingBag01Icon,
  sidebarBottom: SidebarBottomIcon,
  sidebarLeft: SidebarLeft01Icon,
  sidebarRight: SidebarRight01Icon,
  slidersHorizontal: SlidersHorizontalIcon,
  smile: SmileIcon,
  solidLine: SolidLine01Icon,
  sorting: Sorting01Icon,
  squareLock: SquareLock01Icon,
  table: Table01Icon,
  tag: Tag01Icon,
  tap: Tap01Icon,
  text: TextIcon,
  textFont: TextFontIcon,
  textSquare: TextSquareIcon,
  toggleOff: ToggleOffIcon,
  toggleOn: ToggleOnIcon,
  translate: TranslateIcon,
  chevronDown: ChevronDownIcon,
  userCircle: UserCircleIcon,
} as const

export type IconName = keyof typeof Icons

export type IconData = (typeof Icons)[IconName]

export interface RegisteredIcon {
  name: IconName
  label: string
  icon: IconData
  category: IconCategoryId
}

/** Flat list with display labels and categories, e.g. for icon galleries. */
export const iconRegistry: RegisteredIcon[] = [
  // Actions
  { name: "copy", label: "Copy", icon: Icons.copy, category: "actions" },
  { name: "delete", label: "Delete", icon: Icons.delete, category: "actions" },
  { name: "share", label: "Share", icon: Icons.share, category: "actions" },
  { name: "plus", label: "Plus", icon: Icons.plus, category: "actions" },
  { name: "minus", label: "Minus", icon: Icons.minus, category: "actions" },
  // Arrows & Navigation
  { name: "arrowLeft", label: "Arrow Left", icon: Icons.arrowLeft, category: "arrows" },
  { name: "arrowRight", label: "Arrow Right", icon: Icons.arrowRight, category: "arrows" },
  { name: "arrowUp", label: "Arrow Up", icon: Icons.arrowUp, category: "arrows" },
  { name: "arrowDown", label: "Arrow Down", icon: Icons.arrowDown, category: "arrows" },
  { name: "chevronRight", label: "Chevron Right", icon: Icons.chevronRight, category: "arrows" },
  { name: "arrowLeftRight", label: "Arrow Left Right", icon: Icons.arrowLeftRight, category: "arrows" },
  { name: "arrowExpand", label: "Expand", icon: Icons.arrowExpand, category: "arrows" },
  { name: "minimize", label: "Minimize", icon: Icons.minimize, category: "arrows" },
  { name: "chevronDown", label: "Chevron Down", icon: Icons.chevronDown, category: "arrows" },
  { name: "navigation", label: "Navigation", icon: Icons.navigation, category: "arrows" },
  { name: "route", label: "Route", icon: Icons.route, category: "arrows" },
  // Commerce
  { name: "shoppingBag", label: "Shopping Bag", icon: Icons.shoppingBag, category: "commerce" },
  { name: "tag", label: "Tag", icon: Icons.tag, category: "commerce" },
  // Communication
  { name: "comment", label: "Comment", icon: Icons.comment, category: "communication" },
  { name: "message", label: "Message", icon: Icons.message, category: "communication" },
  { name: "chatting", label: "Chatting", icon: Icons.chatting, category: "communication" },
  { name: "bubbleChat", label: "Bubble Chat", icon: Icons.bubbleChat, category: "communication" },
  { name: "attachment", label: "Attachment", icon: Icons.attachment, category: "communication" },
  { name: "inbox", label: "Inbox", icon: Icons.inbox, category: "communication" },
  { name: "sent", label: "Sent", icon: Icons.sent, category: "communication" },
  // Data
  { name: "table", label: "Table", icon: Icons.table, category: "data" },
  { name: "analytics", label: "Analytics", icon: Icons.analytics, category: "data" },
  // Forms
  { name: "edit", label: "Edit", icon: Icons.edit, category: "forms" },
  { name: "textSquare", label: "Text Square", icon: Icons.textSquare, category: "forms" },
  { name: "note", label: "Note", icon: Icons.note, category: "forms" },
  { name: "rowInsert", label: "Row Insert", icon: Icons.rowInsert, category: "forms" },
  { name: "squareLock", label: "Square Lock", icon: Icons.squareLock, category: "forms" },
  { name: "checkmarkSquare", label: "Checkmark Square", icon: Icons.checkmarkSquare, category: "forms" },
  { name: "radioButton", label: "Radio Button", icon: Icons.radioButton, category: "forms" },
  { name: "toggleOn", label: "Toggle On", icon: Icons.toggleOn, category: "forms" },
  { name: "toggleOff", label: "Toggle Off", icon: Icons.toggleOff, category: "forms" },
  { name: "slidersHorizontal", label: "Sliders", icon: Icons.slidersHorizontal, category: "forms" },
  { name: "checkList", label: "Check List", icon: Icons.checkList, category: "forms" },
  // Interface
  { name: "search", label: "Search", icon: Icons.search, category: "interface" },
  { name: "settings", label: "Settings", icon: Icons.settings, category: "interface" },
  { name: "more", label: "More", icon: Icons.more, category: "interface" },
  { name: "cursorPointer", label: "Cursor Pointer", icon: Icons.cursorPointer, category: "interface" },
  { name: "tap", label: "Tap", icon: Icons.tap, category: "interface" },
  { name: "keyboard", label: "Keyboard", icon: Icons.keyboard, category: "interface" },
  { name: "sorting", label: "Sorting", icon: Icons.sorting, category: "interface" },
  { name: "searchList", label: "Search List", icon: Icons.searchList, category: "interface" },
  { name: "command", label: "Command", icon: Icons.command, category: "interface" },
  { name: "menu", label: "Menu", icon: Icons.menu, category: "interface" },
  { name: "mouseRightClick", label: "Right Click", icon: Icons.mouseRightClick, category: "interface" },
  { name: "listNumber", label: "Numbered List", icon: Icons.listNumber, category: "interface" },
  { name: "mouse", label: "Mouse", icon: Icons.mouse, category: "interface" },
  { name: "resize", label: "Resize", icon: Icons.resize, category: "interface" },
  { name: "listView", label: "List View", icon: Icons.listView, category: "interface" },
  { name: "userCircle", label: "User Circle", icon: Icons.userCircle, category: "interface" },
  { name: "solidLine", label: "Solid Line", icon: Icons.solidLine, category: "interface" },
  { name: "calendar", label: "Calendar", icon: Icons.calendar, category: "interface" },
  { name: "clock", label: "Clock", icon: Icons.clock, category: "interface" },
  { name: "globe", label: "Globe", icon: Icons.globe, category: "interface" },
  { name: "translate", label: "Translate", icon: Icons.translate, category: "interface" },
  // Layout
  { name: "grid", label: "Grid", icon: Icons.grid, category: "layout" },
  { name: "layout", label: "Layout", icon: Icons.layout, category: "layout" },
  { name: "layers", label: "Layers", icon: Icons.layers, category: "layout" },
  { name: "sidebarLeft", label: "Sidebar Left", icon: Icons.sidebarLeft, category: "layout" },
  { name: "sidebarRight", label: "Sidebar Right", icon: Icons.sidebarRight, category: "layout" },
  { name: "sidebarBottom", label: "Sidebar Bottom", icon: Icons.sidebarBottom, category: "layout" },
  { name: "appWindow", label: "App Window", icon: Icons.appWindow, category: "layout" },
  { name: "appWindowMac", label: "App Window (Mac)", icon: Icons.appWindowMac, category: "layout" },
  { name: "browser", label: "Browser", icon: Icons.browser, category: "layout" },
  // Media & Design
  { name: "colors", label: "Colors", icon: Icons.colors, category: "media" },
  { name: "textFont", label: "Text Font", icon: Icons.textFont, category: "media" },
  { name: "text", label: "Text", icon: Icons.text, category: "media" },
  { name: "blur", label: "Blur", icon: Icons.blur, category: "media" },
  { name: "crop", label: "Crop", icon: Icons.crop, category: "media" },
  { name: "carouselHorizontal", label: "Carousel", icon: Icons.carouselHorizontal, category: "media" },
  { name: "highlighter", label: "Highlighter", icon: Icons.highlighter, category: "media" },
  // Status & Feedback
  { name: "alert", label: "Alert Circle", icon: Icons.alert, category: "status" },
  { name: "check", label: "Check", icon: Icons.check, category: "status" },
  { name: "loading", label: "Loading", icon: Icons.loading, category: "status" },
  { name: "infoCircle", label: "Info Circle", icon: Icons.infoCircle, category: "status" },
  { name: "helpCircle", label: "Help Circle", icon: Icons.helpCircle, category: "status" },
  { name: "helpSquare", label: "Help Square", icon: Icons.helpSquare, category: "status" },
  { name: "progress", label: "Progress", icon: Icons.progress, category: "status" },
  { name: "notification", label: "Notification", icon: Icons.notification, category: "status" },
]

type IconProps = React.ComponentProps<typeof HugeiconsIcon>

/** HugeiconsIcon with the app-wide default stroke width. */
export function Icon({ strokeWidth, className, ...props }: IconProps) {
  return <HugeiconsIcon strokeWidth={strokeWidth} className={cn("text-muted-foreground hover:text-foreground transition-colors", className)} {...props} />
}
