"use client"

import * as React from "react"

import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { ScrollArea } from "@/components/ui/scroll-area"

const LAST_UPDATED = "August 3, 2026"

const SECTIONS = [
  {
    title: "1. Accepting these terms",
    body: "By creating an account or using AI Ellie you agree to these terms. If you are using the service for an organisation, you confirm you are allowed to accept them on its behalf.",
  },
  {
    title: "2. Your account",
    body: "You sign in with a verification code sent to your email address. Keep access to that inbox secure — anything done from your account is treated as done by you. Tell us straight away if you think someone else has access.",
  },
  {
    title: "3. Acceptable use",
    body: "Do not use the service to break the law, infringe someone else's rights, generate malware, harass people, or attempt to bypass rate limits and safety systems. We may suspend accounts that do.",
  },
  {
    title: "4. Your content and AI output",
    body: "You keep ownership of what you submit and, as between you and us, of the responses you receive. Output is generated by a model and can be wrong — check anything you rely on, especially legal, medical or financial matters.",
  },
  {
    title: "5. Plans and billing",
    body: "Paid plans renew automatically for the period you selected until you cancel. Cancelling stops the next renewal and keeps access until the end of the current period. Fees already paid are non-refundable unless the law says otherwise.",
  },
  {
    title: "6. Intellectual property",
    body: "The service, its interface and its design system remain ours. These terms grant you a limited, non-exclusive, non-transferable right to use the service, and nothing more.",
  },
  {
    title: "7. Termination",
    body: "You can close your account at any time. We may suspend or end access if you materially breach these terms, or if we are required to by law. You can export your data before you leave.",
  },
  {
    title: "8. Disclaimers and liability",
    body: "The service is provided “as is”, without warranties of any kind. To the extent the law allows, our total liability is limited to the amount you paid us in the twelve months before the claim.",
  },
  {
    title: "9. Changes",
    body: "We may update these terms. Material changes are announced in the product at least 30 days before they take effect, and continuing to use the service means you accept them.",
  },
  {
    title: "10. Contact",
    body: "Questions about these terms can be sent to legal@aiellie.dev.",
  },
]

export function TermsOfServiceDialog({
  trigger,
  className,
  ...props
}: React.ComponentProps<typeof Dialog> & {
  trigger?: React.ReactNode
  className?: string
}) {
  return (
    <Dialog {...props}>
      <DialogTrigger
        render={
          <button
            type="button"
            className={cn(
              "underline underline-offset-4 transition-colors hover:text-primary",
              className
            )}
          />
        }
      >
        {trigger ?? "Terms of Service"}
      </DialogTrigger>
      <DialogContent className="sm:max-w-lg">
        <DialogHeader>
          <DialogTitle>Terms of Service</DialogTitle>
          <DialogDescription>
            The agreement between you and AI Ellie. Last updated {LAST_UPDATED}.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="-me-2 h-[min(55vh,26rem)] pe-4">
          <div className="flex flex-col gap-4 text-sm text-muted-foreground">
            {SECTIONS.map((section) => (
              <section key={section.title} className="flex flex-col gap-1">
                <h3 className="font-medium text-foreground">{section.title}</h3>
                <p className="leading-normal">{section.body}</p>
              </section>
            ))}
          </div>
        </ScrollArea>
        <DialogFooter>
          <DialogClose render={<Button variant="outline" />}>Close</DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
